# Generated by Django 5.0.4 on 2024-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categorie_description_alter_product_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sub_categorie',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
