# Generated by Django 5.0.4 on 2024-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_categorie_deleted_at_sub_categorie_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_attribute',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products_sku',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_categorie',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
