# Generated by Django 5.0.4 on 2024-05-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_categorie_deleted_at_alter_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attribute',
            name='value',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='products_sku',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products_sku',
            name='sku',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='sub_categorie',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
