# Generated by Django 5.0.4 on 2024-05-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_attribute_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sub_categorie'),
        ),
    ]
