# Generated by Django 5.0.4 on 2024-05-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_products_sku_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
